import Head from 'next/head'
import Image from 'next/image'
import About from './About'
import Homepage from './Homepage'
import KnowMore from './KnowMore'


export default function Home() {
  return (
    <div>
      <Head>
        <title>SoulMusic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/chatbot.ico" />
      </Head>
      <Homepage/> 
      
    </div>
  )
}
